# render.yaml
services:
  - type: web
    name: grokbit-backend
    env: python
    buildCommand: cd app && pip install -r ../requirements.txt
    startCommand: cd app && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: XAI_API_KEY
        valueFrom:
          secretKeyRef:
            name: xai-api-key
      - key: PORT
        value: 10000